# Tendermint Configuration Template
# For TrustNet node deployment

[main]
home = "/home/warden/.tendermint"
level = "info"

[rpc]
laddr = "tcp://0.0.0.0:26657"
grpc_laddr = ""
unsafe = false

[p2p]
laddr = "tcp://0.0.0.0:26656"
persistent_peers = ""
addr_book_strict = true

[consensus]
timeout_propose = "1s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "5s"

[mempool]
version = "v1"
recheck = true
recheck_timeout = 0
max_tx_bytes = 1048576
max_batch_bytes = 0

[storage]
discard_abci_responses = false

[tx_index]
indexer = "kv"
psql_conn = ""
